services:
  postgres:
    image: 'postgres:latest'
    container_name: medicalSchedule
    environment:
      - 'POSTGRES_DB=medicalSchedule_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
    restart: always